const clientLogoPath = (filename) => `/client/pdf-profile-images/${filename}`;

export const clientRecords = [
  { filename: "indian-railways.jpg", label: "Indian Railways" },
  { filename: "hindustan-petroleum.png", label: "Hindustan Petroleum" },
  { filename: "state-bank-of-india.png", label: "State Bank of India" },
  { filename: "powergrid.jpg", label: "Power Grid Corporation of India" },
  { filename: "coal-india.jpg", label: "Coal India Limited" },
  { filename: "delhi-govt.jpg", label: "Delhi Government" },
  { filename: "government-nct-delhi.jpg", label: "Government of NCT of Delhi" },
  { filename: "government-madhya-pradesh.jpg", label: "Government of Madhya Pradesh" },
  { filename: "government-bihar.jpg", label: "Government of Bihar" },
  { filename: "ministry-of-coal.jpg", label: "Ministry of Coal" },
  { filename: "ministry-of-textiles.jpg", label: "Ministry of Textiles" },
  { filename: "ministry-of-home-affairs.png", label: "Ministry of Home Affairs" },
  { filename: "ministry-of-civil-aviation.jpg", label: "Ministry of Civil Aviation" },
  { filename: "mhrd.jpg", label: "Ministry of Education" },
  { filename: "airports-authority-of-india.png", label: "Airports Authority of India" },
  { filename: "hindustan-aeronautics-limited.jpg", label: "Hindustan Aeronautics Limited" },
  { filename: "reliance-industries.jpg", label: "Reliance Industries Limited" },
  { filename: "seva-automotive.jpg", label: "Seva Automotive" },
  { filename: "smart-city-mission.jpg", label: "Smart Cities Mission" },
  { filename: "government-telangana.jpg", label: "Government of Telangana" },
  { filename: "government-tamil-nadu.jpg", label: "Government of Tamil Nadu" },
  { filename: "government-punjab.jpg", label: "Government of Punjab" },
  { filename: "government-odisha.jpg", label: "Government of Odisha" },
  { filename: "government-maharashtra.jpg", label: "Government of Maharashtra" },
  { filename: "government-gujarat.jpg", label: "Government of Gujarat" },
  { filename: "government-kerala.png", label: "Government of Kerala" },
  { filename: "drdo.jpg", label: "Defence Research and Development Organisation" },
  { filename: "defence-ministry.jpg", label: "Ministry of Defence" },
  { filename: "government-uttar-pradesh.jpg", label: "Government of Uttar Pradesh" },
  { filename: "central-reserve-police-force.jpg", label: "Central Reserve Police Force" },
  { filename: "kendriya-bhandar.jpg", label: "Kendriya Bhandar" },
  { filename: "indian-army.png", label: "Indian Army" },
  { filename: "border-security-force.jpg", label: "Border Security Force" },
  { filename: "itbp.jpg", label: "Indo-Tibetan Border Police" },
].map((client) => ({
  ...client,
  src: clientLogoPath(client.filename),
}));
